### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by Eeems**
Building is current broken due to missing requirements and breaking changes to React. This PR fixes those and will resolve the issue @dagomar mentions in #51

### CODE REVIEW

**Comment by dagomar** [comment]
Hi Eems,

I was finally able to test, but this doesn't seem to have resolved my issue. I've checkout out your version and did an npm install, then web-ext run, and the problem persist. Is there any way I can assist or provide you with more information?

**Comment by Eeems** [comment]
@dagomar (It's Eeems not Eems btw)
Could you use [about:debugging](about:debuggin) to provide me with the output of the console when you attempt to open the dialog? Could you also provide me with the output of [about:buildconfig](about:buildconfig)

**Comment by dagomar** [comment]
Hi @Eeems,

Here's the information you asked for, thanks for looking into this. First about:debugging:

image

(This is printed in the console)
`Could not map contract ID '@mozilla.org/widget/printdialog-service;1' to CID {06beec76-a183-4d9f-85dd-085f26da565a} because no implementation of the CID is registered.
Loading failed for the <script> with source “moz-extension://707f3886-d669-4f34-95da-3b620e12742a/public/js/events.js”. _generated_background_page.html:6:1`

The next is about:buildconfig:
`about:buildconfig
Source

Built from https://hg.mozilla.org/releases/mozilla-release/rev/c58ea2229c337e9981ab9d3650b04fd3d249b141
Build platform
target
x86_64-pc-mingw32
Build tools
Compiler 	Version 	Compiler flags
z:/build/build/src/clang/bin/clang-cl.exe -Xclang -std=gnu99 -fms-compatibility-version=19.15.26726 	19.15.26726 	-nologo -wd4091 -D_HAS_EXCEPTIONS=0 -W3 -Gy -Zc:inline -Gw -wd4244 -wd4267 -Wno-unknown-pragmas -Wno-ignored-pragmas -Wno-deprecated-declarations -Wno-invalid-noreturn -we4553
z:/build/build/src/clang/bin/clang-cl.exe -fms-compatibility-version=19.15.26726 	19.15.26726 	-Qunused-arguments -Qunused-arguments -TP -nologo -w15038 -wd5026 -wd5027 -Zc:sizedDealloc- -wd4091 -wd4577 -D_HAS_EXCEPTIONS=0 -W3 -Gy -Zc:inline -Gw -wd4251 -wd4244 -wd4267 -wd4800 -wd4595 -wd4065 -Wno-inline-new-delete -Wno-invalid-offsetof -Wno-microsoft-enum-value -Wno-microsoft-include -Wno-unknown-pragmas -Wno-ignored-pragmas -Wno-deprecated-declarations -Wno-invalid-noreturn -Wno-inconsistent-missing-override -Wno-implicit-exception-spec-mismatch -Wno-unused-local-typedef -Wno-ignored-attributes -Wno-used-but-marked-unused -we4553 -D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING -GR- -Zi -O2 -Oy
Configure options

MOZ_AUTOMATION=1 'MOZILLABUILD=C:\mozilla-build' --host=x86_64-pc-mingw32 --target=x86_64-pc-mingw32 --enable-update-channel=release MOZILLA_OFFICIAL=1 MOZ_PGO=1 CC=clang-cl CXX=clang-cl WINDOWSSDKDIR=z:/build/build/src/vs2017_15.8.4/SDK LINKER=lld-link MAKECAB=z:/build/build/src/makecab.exe ENABLE_CLANG_PLUGIN=1 --enable-jemalloc LLVM_CONFIG=z:/build/build/src/clang/bin/llvm-config RUSTC=z:/build/build/src/rustc/bin/rustc CARGO=z:/build/build/src/rustc/bin/cargo RUSTDOC=z:/build/build/src/rustc/bin/rustdoc CBINDGEN=z:/build/build/src/cbindgen/cbindgen RUSTFMT=z:/build/build/src/rustc/bin/rustfmt --enable-js-shell NODEJS=z:/build/build/src/node/node.exe --with-mozilla-api-keyfile=c:/builds/mozilla-desktop-geoloc-api.key --with-google-api-keyfile=c:/builds/gapi.data --enable-rust-simd --enable-verify-mar MAKE=z:/build/build/src/mozmake.EXE --enable-crashreporter --enable-official-branding`

**Comment by Eeems** [comment]
@dagomar while the console was open did you attempt to open the addon? I'm not seeing any errors that would cause this.
Could you also provide me with the steps you took in order to run the addon?

**Comment by Eeems** [comment]
@dagomar I'm going to ask the following again:
> while the console was open did you attempt to open the addon? I'm not seeing any errors that would cause this.

**Comment by dagomar** [comment]
Hi @Eeems 

Looks like something went wrong with the building of the assets, it was missing a js file. I rebuild and now it looks like it is working. Thanks for your patience!

**Comment by Eeems** [comment]
@alanhamlett Any chance you'll be merging this soon?

**Comment by Eeems** [comment]
@alanhamlett poke?

**Comment by alanhamlett** [comment]
Thanks!

**Pull request merged**
