### PR TITLE
Add ability to use wildcard in white/black url lists

### PR DESCRIPTION
**Pull request by toptalo**
Hello! I have try to add wildcard support in url lists.

To add ability to use `http://*.local` for example

But for some reason can't run tests locally: get en error `SyntaxError: Unexpected token import`

### CODE REVIEW

**Comment by alanhamlett** [comment]
Thanks!

**Comment by toptalo** [comment]
Wow! Thank you!

**Comment by boxsnake** [comment]
Cool work. Thanks!

**Comment by kanatkubash** [comment]
Thank you

**Comment by teckel12** [comment]
In reference to #66 , will this PR address the following correctly?

`http?://*.domain.com`

**Comment by toptalo** [comment]
This line will be replaced to `/http?:\/\/.*.domain.com/`

**Comment by dimateos** [comment]
Do this still work? Then consider mentioning this somewhere (web, chrome store), or at list show an example. Thanks!

**Pull request merged**
